var dir_08d237fc27d4ecd563f71c5d52f2fecc =
[
    [ "accel.c", "accel_8c.html", "accel_8c" ],
    [ "accel.h", "accel_8h.html", "accel_8h" ],
    [ "Events.c", "_events_8c.html", null ],
    [ "Events.h", "_events_8h.html", null ],
    [ "FIFO.c", "_f_i_f_o_8c.html", "_f_i_f_o_8c" ],
    [ "FIFO.h", "_f_i_f_o_8h.html", "_f_i_f_o_8h" ],
    [ "Flash.c", "_flash_8c.html", "_flash_8c" ],
    [ "Flash.h", "_flash_8h.html", "_flash_8h" ],
    [ "FTM.c", "_f_t_m_8c.html", "_f_t_m_8c" ],
    [ "FTM.h", "_f_t_m_8h.html", "_f_t_m_8h" ],
    [ "I2C.c", "_i2_c_8c.html", "_i2_c_8c" ],
    [ "I2C.h", "_i2_c_8h.html", "_i2_c_8h" ],
    [ "LEDs.c", "_l_e_ds_8c.html", "_l_e_ds_8c" ],
    [ "LEDs.h", "_l_e_ds_8h.html", "_l_e_ds_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "median.c", "median_8c.html", "median_8c" ],
    [ "median.h", "median_8h.html", "median_8h" ],
    [ "packet.c", "packet_8c.html", "packet_8c" ],
    [ "packet.h", "packet_8h.html", "packet_8h" ],
    [ "PIT.c", "_p_i_t_8c.html", "_p_i_t_8c" ],
    [ "PIT.h", "_p_i_t_8h.html", "_p_i_t_8h" ],
    [ "RTC.c", "_r_t_c_8c.html", "_r_t_c_8c" ],
    [ "RTC.h", "_r_t_c_8h.html", "_r_t_c_8h" ],
    [ "types.h", "types_8h.html", [
      [ "int16union_t", "unionint16union__t.html", "unionint16union__t" ],
      [ "uint16union_t", "unionuint16union__t.html", "unionuint16union__t" ],
      [ "uint32union_t", "unionuint32union__t.html", "unionuint32union__t" ],
      [ "uint64union_t", "unionuint64union__t.html", "unionuint64union__t" ],
      [ "TFloat", "union_t_float.html", "union_t_float" ]
    ] ],
    [ "UART.c", "_u_a_r_t_8c.html", "_u_a_r_t_8c" ],
    [ "UART.h", "_u_a_r_t_8h.html", "_u_a_r_t_8h" ]
];